### ISSUE TITLE
Broyden updates

### ISSUE THREAD

**Issue by stevengj** [JuliaNLSolvers/NLsolve.jl#1]
One of my students last semester did an extensive study of Broyden updates for his final project (compared to finite-differencing etc.).   In order to get good performance (e.g. to beat Matlab's `fsolve` and Sundials' `kinsol`, both of which use finite differences), it turns out that you need to be somewhat careful about how to do the line searches, and you occasionally may need to "restart" with a finite-difference Jacobian if progress stagnates, and these practical robustness issues weren't described well in the literature.

It would be good to touch base with him before banging on that feature (which should be pretty easy to implement once you know the tricks). I think he would be willing to share his paper and his (Matlab) code as a starting point; I don't think he has a github account, but I could check with him if you like.

**Comment by KristofferC** [comment]
Please comment if there is anything to do here

**Comment by stevengj** [comment]
There is no implementation of a Broyden algorithm in NLsolve.jl, so this issue still seems open.

**Comment by jmartin3** [comment]
Let me know if I can be of any help on this.

Thanks,
Jeff

**Comment by pkofod** [comment]
hey, it only took 5 years to get around to this :fireworks:
