### ISSUE TITLE
mcpsolve returns wrong answer near one of the limits

### ISSUE THREAD

**Issue by djsegal** [JuliaNLSolvers/NLsolve.jl#102]
If you do:

`nlsolve(magnet_equation_set!,x0).zero`

or

```
mcpsolve(
  magnet_equation_set!, [-Inf, -Inf], [+Inf, +Inf], cur_initial_values, xtol = 5e-8
).zero
```

you get `[0.844365,0.33534]`  // the value I want

----------------------

however, if you change `[-Inf, -Inf]` to `[0, 0]`, you get a very wrong answer:

```
mcpsolve(
  magnet_equation_set!, [0.0, 0.0], [+Inf, +Inf], cur_initial_values, xtol = 5e-8
).zero
```

yields: `[-2.62852e-15,-3.51704e-9]`

---------------------

Why is setting `[0, 0]` as bottom bounds giving such crazy answers?

**Comment by sglyon** [comment]
Hmm... that doesn't look too good.

I'm actually not sure what would be causing this problem. Sorry for the unhelpful response... Maybe someone else has ideas?

**Comment by djsegal** [comment]
One note is that:

+ `xtol` above is set to 5e-8.
+ the second solution is `-3.51704e-9`

Could it just be catching wind of the trivial solution and then slowing down near it?

**Comment by pkofod** [comment]
What is `magnet_equation_set!`? Why is `[-2.62852e-15,-3.51704e-9]` not a solution?

**Comment by sglyon** [comment]
One more thing to note is that the mixed complementarity problem is _not_ a box constrained nonlinear system. 

There are specific requirements on the _sign_ of the original system of equations at the bounds you set.

From the readme

> Given a multivariate function `f` and two vectors `a` and `b`, the solution to
the mixed complementarity problem (MCP) is a vector `x` such that one of the
following holds for every index `i`:
> 
> * either `f_i(x) = 0` and `a_i <= x_i <= b_i`
> * or `f_i(x) > 0` and `x_i = a_i`
> * or `f_i(x) < 0` and `x_i = b_i`

The solver returning `[-2.62852e-15,-3.51704e-9]` (which is within `xtol` of  the lower bounds) must mean that at the lower that point the objective function is positive, which satisfies the requirements for `[-2.62852e-15,-3.51704e-9]` to be a solution to the mixed complementarity problem.

**Comment by djsegal** [comment]
This is probably to vague to be helpful. Closing
