### ISSUE TITLE
Change f!(x, fvec) to f!(fvec, x)

### ISSUE THREAD

**Issue by matthieugomez** [JuliaNLSolvers/NLsolve.jl#110]
It would be nice to change the order of storage arrays and evaluation point arrays in f! and g! calls, to match Julia usual syntax and [Optim v0.9](https://github.com/JuliaNLSolvers/Optim.jl/blob/master/NEWS.md)

**Comment by ChrisRackauckas** [comment]
Please make sure to PR METADATA to upper bound dependencies when this happens, with a note about the change.

**Comment by pkofod** [comment]
> Please make sure to PR METADATA to upper bound dependencies when this happens, with a note about the change.

Sure... In Optim we've simply deprecated it, but it does incur something like one extra gradient call and a couple of function calls.

**Comment by ChrisRackauckas** [comment]
Is this going to happen? I think it should be decided and done, or discarded.

**Comment by pkofod** [comment]
It's happening in my next pr
