### ISSUE TITLE
Allow AbstractArray inputs

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaNLSolvers/NLsolve.jl#111]
It would be nice if NLsolve accepted `AbstractArray` inputs `x` and treated internally the `vec(x)`, and just `reshape`d afterwards (and with each function call) to hide this abstraction from the user. Mathematically (and computationally since `vec` and `reshape` are views) there's no difference here, but it takes user burden away.

**Comment by sglyon** [comment]
I'd be fine with that, but one concern I have is whether there any calls to blas or lapack that require a contiguous or strided array.

Any ideas anyone?

**Comment by ChrisRackauckas** [comment]
>I'd be fine with that, but one concern I have is whether there any calls to blas or lapack that require a contiguous or strided array.

Those are handled by generic fallbacks. So you can do BLAS calls on an `AbstractArray`.

**Comment by sglyon** [comment]
Ok cool, sounds like it is PR time
