### ISSUE TITLE
Non-allocating Reusable Form

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaNLSolvers/NLsolve.jl#114]
Many of the inner algorithms do large allocations each times.

https://github.com/JuliaNLSolvers/NLsolve.jl/blob/master/src/newton.jl#L43

This is painful when using NLsolve repeatedly and iteratively in a loop. It would be nice to have a way to keep the cache so that way all of the inner variables can be reused.

**Comment by ChrisRackauckas** [comment]
It would be nice if, in this form, one had some control over when the Jacobian is updated.

**Comment by pkofod** [comment]
Sure, we did that in Optim, so let's do it here as well. Essentially, you're just allowed to pass a sort of "NLsolveCacheVars{T}" sort of type.

> when the Jacobian is updated.

What do you mean, "when" the Jacobian is updated. It's just updated every iteration, no?

**Comment by pkofod** [comment]
Lol, `gr` at https://github.com/JuliaNLSolvers/NLsolve.jl/blob/0b1cdf8edf91f6d6eff6acfe3470e58ae977d031/src/newton.jl#L47 isn't even used

**Comment by pkofod** [comment]
done in the latest tag
