### ISSUE TITLE
Trust Region Newton Methods

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaNLSolvers/NLsolve.jl#116]
Trust region Newton Methods are a mixture of trust region methods and Newton methods that improves the region of convergence while not sacrificing the "good properties" of Newton near a zero. These methods are important when made quasi-Newton because then you don't need to be diligent about having the right Jacobian and can still get good convergence. This means you can reuse the same Jacobian across different related problems and have an increased convergence range over standard quasi-Newton methods.

http://www.numerical.rl.ac.uk/people/nimg/course/lectures/raphael/lectures/lec7slides.pdf
https://www.csie.ntu.edu.tw/~cjlin/papers/logistic.pdf

**Comment by KristofferC** [comment]
Dogleg is implemented...?

**Comment by ChrisRackauckas** [comment]
It's not dogleg.

**Comment by KristofferC** [comment]
Ok, I just saw that from the first slide :P

**Comment by KristofferC** [comment]
But dogleg should just be Newton when you are close to the zero which is what you described
