### ISSUE TITLE
Incompatibility with new LineSearches version

### ISSUE THREAD

**Issue by djsegal** [JuliaNLSolvers/NLsolve.jl#120]
get this error message:

```
julia> Pkg.free("NLSolversBase")
INFO: Freeing NLSolversBase
ERROR: fixed packages introduce conflicting requirements for NLSolversBase:
         LineSearches requires versions [3.0.0,∞)
         NLsolve requires versions [2.1.0,3.0.0)
       the requirements are unsatisfiable because their intersection is empty
```

-------

is there any plan to update to using the new version of `NLSolversBase`?

**Comment by sglyon** [comment]
The only thing blocking this is somebody finding the time to adapt to the new APIs and open a PR.

cc @pkofod @KristofferC

**Comment by pkofod** [comment]
How did you make this happen? Did you manually check out some of the related packages?

**Comment by pkofod** [comment]
btw, fwiw it's fixed here https://github.com/JuliaNLSolvers/NLsolve.jl/pull/117 I'm just waiting for response from @devmotion

**Comment by pkofod** [comment]
This is tagged now, please return if you don't find a solution.
