### ISSUE TITLE
Don't use void tags in autodiff

### ISSUE THREAD

**Issue by simonbyrne** [JuliaNLSolvers/NLsolve.jl#126]
Once https://github.com/JuliaDiff/ForwardDiff.jl/pull/279 is fixed, it should be easier to use non-Void tags in the autodiff machinery. This will allow optimisation over functions which themselves use Dual numbers.

e.g. see https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/issues/200

**Comment by pkofod** [comment]
Permission granted to re-ping once it is merged and I'd love to take care of it.
