### ISSUE TITLE
Implementation of "simple iteration" for the `fixedpoint` inplace functions

### ISSUE THREAD

**Issue by jlperla** [JuliaNLSolvers/NLsolve.jl#149]
After #148  is done:  Implement the inplace version of the algorithm (what is currently in `fixedpointOLD!`).  This might take a little work to figure out what is going on in the other algorithms, and you can ask Patrick for advice.  If you are having trouble then we can push it off.

The key is that the `df` function is a generic wrapper for the function which can give you information about whether it is an inplace function or not.

**Comment by ArnavSood** [comment]
Closing this, since this is included in the open PR and test suite.
