### ISSUE TITLE
Support newton iteration with the fixedpoint

### ISSUE THREAD

**Issue by jlperla** [JuliaNLSolvers/NLsolve.jl#151]
We can use the existing implementation in `nlsolve` to let `fixedpoint` use newton's method.

Lets say we want the fixed point of a $f(x)$ and they may pass in an analytic derivative $f'(x)$ where x is N dimensional vector.

There are a few different cases depending on what type of function is passed in:
- If they pass in an analytical derivative, then define a new function $h(x) = f(x) - x$ and a new derivative $h'(x) = f'(x) - I_n$ (with the identity matrix) and call `nlsolve` directly with those new functions
- If they pass in no analytical derivative and want to use auto-differentation, then just pass the $h(x) = f(x) - x$ function directly to `nlsolve`
- You may need to be careful with inplace vs. outplace of the functions when you define the new g

**Comment by jlperla** [comment]
Also, need to test a sparse vs. nonsparse jacobian

**Comment by jlperla** [comment]
Down the road, it is probably worth the trouble to implement the direct newton's method for fixed point problems as a comparison.  See i.e. http://www4.ncsu.edu/~ctk/TALKS/Anderson.pdf for example.

**Comment by ChrisRackauckas** [comment]
Why? It would just be a repeat of the same code.

**Comment by ChrisRackauckas** [comment]
Here's SciPy for example, and it mixes the fixed point methods into the nonlinear solvers for this same reason as well:

https://docs.scipy.org/doc/scipy-1.0.0/reference/optimize.nonlin.html

**Comment by jlperla** [comment]
The only reason to consider it down the road would be to potentially make it a little more efficient (e.g. don't need to auto-differentiate a wrapper function), and only with benchmarking.

My gut is it wouldn't matter for newton but might make a difference for anderson.  The anderson algorithm is designed for fixed points and it has to convert a system of equations to a fixed point problem, so when converting a fixed point problem to a nonlinear system to a fixed point problem it is worth testing out if the direct implementation is faster.

**Comment by ChrisRackauckas** [comment]
>e.g. don't need to auto-differentiate a wrapper function

How is that slower? It's inlined. 

>potentially make it a little more efficient

What part can be written differently? Can you point to somewhere in the code you'd be able to better optimize?
