### ISSUE TITLE
Solver slow when using BigFloat

### ISSUE THREAD

**Issue by shakisparki** [JuliaNLSolvers/NLsolve.jl#178]
I found out that in scenarios where I need more machine precision in order to meet tolerance values, and I use the BigFloat datatype, the solver becomes much much slower (takes longer for each iteration) especially as the number of unknowns increases.

**Comment by antoine-levitt** [comment]
BigFloats are slow, yes. Not much nlsolve can do there.

**Comment by pkofod** [comment]
Try ArbFloat, double-double approaches or similar. I can write a tutorial. I don’t know for a fact that all extended precision types work, but if they don’t, I’ll consider it a bug.
