### ISSUE TITLE
Unsatisfiable requirements

### ISSUE THREAD

**Issue by pnvolkmar** [JuliaNLSolvers/NLsolve.jl#185]
ERROR: Unsatisfiable requirements detected for package NLSolversBase:
├─version range [6.1.1,6.1.1+) set by an explicit requirement
└─version range [0.0.1,5.0.0) required by package NLsolve, whose allowed version range is [0.0
.0-,∞):
  └─version range [0.0.0-,∞) set by an explicit requirement
The intersection of the requirements is empty.

I'm trying to address this by pinning (Pkg.pin("NLSolversBase", v"3.1.0")) NLsolversBase and updating my REQUIRE file, but that's resulted in a cascade of other pins and updates to REQUIRE: Optim and LineSearches. It says it's working, but this has been painful. Using Julia 0.6.4.1

**Comment by pkofod** [comment]
Sorry, but what are you trying to do here? Install NLsolve and Optim at the same time?

**Comment by pnvolkmar** [comment]
Install NLsolve at all

**Comment by pkofod** [comment]
from a 100% clean install?

**Comment by pnvolkmar** [comment]
Yeah. On windows 10.

**Comment by pkofod** [comment]
Oh, is this JuliaPro?

**Comment by pnvolkmar** [comment]
Yes

**Comment by pkofod** [comment]
There are some issues with installing packages on JuliaPro because the assumption (I think, don't quote me on that, I don't use JuliaPro myself) is that you're going to be using that particular setup. Maybe ask on discourse?
