### ISSUE TITLE
`nlsolve` allocates a Jacobian even when using `anderson`

### ISSUE THREAD

**Issue by antoine-levitt** [JuliaNLSolvers/NLsolve.jl#202]
The basic `nlsolve(f,x0,method=:anderson)` allocates a dense jacobian. This breaks large systems where a dense jacobian doesn't fit into memory.

**Comment by antoine-levitt** [comment]
While we're at it: NLsolve doesn't support NonDifferentiable.

**Comment by antoine-levitt** [comment]
Workaround: trick OnceDifferentiable into thinking you have a custom jacobian: `OnceDifferentiable(F!,identity,x0,x0,[])`

**Comment by pkofod** [comment]
Thanks, ill fix it unless you do :)

**Comment by antoine-levitt** [comment]
I'd rather you do it if it's easy for you :-) I'm not very comfortable around the NDifferentiable code.

**Comment by pkofod** [comment]
Ill do it :)

**Comment by pkofod** [comment]
#203 . It’s just a quick “do something that works”, but I’ll come back to it. But it works I think ;)

**Comment by antoine-levitt** [comment]
Many thanks, and merry christmas :-)
