### ISSUE TITLE
Restricting solver to positive varriable values

### ISSUE THREAD

**Issue by TorkelE** [JuliaNLSolvers/NLsolve.jl#207]
I have a system of n function of n variables, and would like to find a solution to it. I know that there are several solutions, but am quite certain that there are only one for non-negative variable values (there is at least one such value).

Is there any good way to restrict the solver to not look for solutions with negative values?

**Comment by pkofod** [comment]
Do you experience the iterates having negative values?

**Comment by TorkelE** [comment]
Yes, I give a strictly non negative initial value and find a solution for negative value. However, this might be due to me not providing a jacobian.
(I switched to using JuMP, a suggested possibility in the description, as it allows to restrict to non negative variable values)

**Comment by pkofod** [comment]
There are some possibilities to enforce such constraints, but it's sadly not implemented yet.

**Comment by TorkelE** [comment]
Ok, good to know.
