### ISSUE TITLE
MethodError: Cannot `convert` an object of type CartesianIndex{3} to an object of type Int64

### ISSUE THREAD

**Issue by antoine-levitt** [JuliaNLSolvers/NLsolve.jl#233]
The reproducer is a bit involved, but basically IsFiniteException only accepts Vector{Int} although indices can be more general. Solution is to just untype the indices field?

**Comment by PearsonCHEN** [comment]
Do you solve this problem yet? This error was thrown for the first time I called the function. In the second call, the error disappears. However, it happens all the time when I was debugging.

**Comment by pkofod** [comment]
I untyped it. Thanks
