### ISSUE TITLE
x can become NaN

### ISSUE THREAD

**Issue by jwscook** [JuliaNLSolvers/NLsolve.jl#235]
I've found that `x` can become NaN during a run, but the solve is not terminated. This line 
https://github.com/JuliaNLSolvers/NLsolve.jl/blob/9b4c7b37e6fd2911d1fab77ebeabd450a039712b/src/nlsolve/utils.jl#L19 appears to be related and seems to indicate that NaNs are acceptable, and presumably may turn back to regular numbers. Is this right?

**Comment by pkofod** [comment]
I would not expect them to. That should stop if it sees NaN. I'm not sure why it's written like that. Thanks.

**Comment by jwscook** [comment]
No probs 😄

**Comment by pkofod** [comment]
#244 should fix this
