### ISSUE TITLE
Non-allocating api using StaticVectors

### ISSUE THREAD

**Issue by albop** [JuliaNLSolvers/NLsolve.jl#238]
One tricky part of using and explaining NLsolve is the fact that functions to minimize must not allocate output. Of course it makes perfect sense from a performance perspective. 
I was wondering whether another more intuitive api could be explored using static arrays. You could write: `f(x) = SVector( [ x[1]*2, x[1]+x[2] ] )` and do `OnceDifferentiable(f, SVector[0.1, 0.1], ...)` and the rest would be exactly the same as before, without any performance loss, thanks to static arrays magic. `OnceDifferentiable` would use the type of the second argument to know it needs to define the nonallocating version of `f`.
It would probably be incompatible with the current implementation of automatic differentiation though.

**Comment by albop** [comment]
Hmm, not sure it is relevant, I forgot about the not_inplace option.

**Comment by pkofod** [comment]
NLSolvers.jl has the functionality for this. If you still need it, let me know and I can show you :)
