### ISSUE TITLE
Can call to mul! in newton.ls saved ?

### ISSUE THREAD

**Issue by amartinhuertas** [JuliaNLSolvers/NLsolve.jl#245]
Dear NLsolve.jl developers,

I think that the following call to `mul!`: 

https://github.com/JuliaNLSolvers/NLsolve.jl/blob/master/src/solvers/newton.jl#L94

can be saved if `linesearch isa Static` evaluates to `true`. Note that `cache.g` is only consumed in this line:

https://github.com/JuliaNLSolvers/NLsolve.jl/blob/master/src/solvers/newton.jl#L119

am I right? Is there anything I am missing?

Thanks! @amartinhuertas

**Comment by pkofod** [comment]
Sorry, I didn't see this earlier, let me have a look.

**Comment by pkofod** [comment]
You mean like this right? https://github.com/JuliaNLSolvers/NLsolve.jl/compare/master...pkofod-patch-3?quick_pull=1

**Comment by amartinhuertas** [comment]
> You mean like this right? #249

Yes, indeed! Thanks!

**Comment by pkofod** [comment]
Sorry I didn't tag this change earlier. Had a thesis to finishing writing and hand in :grimacing:  It's merged. I'll tag soon.
