### ISSUE TITLE
Unsatisfiable requirements

### ISSUE THREAD

**Issue by Fiorencio** [JuliaNLSolvers/NLsolve.jl#253]
Hi, I'm getting this incompatibility error. Sorry if this is not the appropriate place for this issue. Thanks for any help.

![image](https://user-images.githubusercontent.com/34515302/96114063-7c2e1480-0ebb-11eb-9b9c-3867d8fe673c.png)

**Comment by pkofod** [comment]
I'm not sure this is NLsolve as such. But you can try to ask on discourse.julialang.org/

**Comment by Fiorencio** [comment]
Thank you. I was not sure either. Best wishes.

Em qua., 16 de dez. de 2020 às 17:17, Patrick Kofod Mogensen <
notifications@github.com> escreveu:
