### ISSUE TITLE
Permission request

### ISSUE THREAD

**Issue by RJDennis** [JuliaNLSolvers/NLsolve.jl#279]
I have written a simple package to solve nonlinear systems with box-constraints.  I would like to use in my readme file the same problem that is used as the simple example in the readme file for NLsolve.jl.  I could come up with my own example, but well yours is already there.  I thought I should ask for permission first.

**Comment by antoine-levitt** [comment]
It's very nice of you to ask for permission (and I'm sure nobody will mind!), but note that the terms of the licence allow you to do this without asking: https://github.com/JuliaNLSolvers/NLsolve.jl/blob/master/LICENSE.md.2
