### ISSUE TITLE
not_in_place + autodiff

### ISSUE THREAD

**Issue by matthieugomez** [JuliaNLSolvers/NLsolve.jl#62]
I cannot use `not_in_place` and `autodiff` at the same time.

``` julia
 nlsolve(not_in_place(x-> x[1] + 2), [0.0], autodiff = true)
ERROR: unrecognized keyword argument "autodiff"
```

**Comment by matthieugomez** [comment]
I'd also like to remove `not_in_place(f, g)` and `not_in_place(f, g, fg)`. 
I think it's neater if `not_in_place` and `n_ary` are just functionals, defined independent from the `DifferentiableFunction` type. 
Someone with a gradient could just do `not_in_place(f), not_in_place(g)`.  That being said, it removes the possibility to use `fg` not in place. But do people really use it?

**Comment by KiranUofG** [comment]
Would it be possible to change the definition of not_in_place from not_in_place(f::function) to just not_in_place(f) ?

I use it for types, which are made callable by modifying the Base Call function. 

It works great when I make this change in my local NLsolve directory. While distributing my package however, I need to ask all my users to make this change in their local installations. 

I'm not sure if making this change would have implications for other applications. 

Please let me know if more info is required.
