### ISSUE TITLE
Does NLsolve want to move in with Optim?

### ISSUE THREAD

**Issue by pkofod** [JuliaNLSolvers/NLsolve.jl#85]
ref: https://github.com/JuliaOpt/Optim.jl/issues/358

Optim is leaving JuliaOpt, as the latter is refocusing, such that it will be an org for MathProgBase, JuMP and extensions, and backend solvers. This means that Optim+LineSearches+LsqFit is looking for a new home; a new org (current most likely name according to the issue above: `JuliaNLSolvers`).

The org is going to contain a quite tightly knit collection of packages: A base package, Optim, LineSearches, some benchmarking and testing packages, and a Least Squares package + curve fitting (LsqFit currently - not sure if there's some refactoring that makes sense there). There's a lot of common code base in there, so it actually does make a lot of sense for us to move.

I was hoping that NLsolve could follow, such that we could get a stack of solver packages (optimization and nonlinear equations solving) written in Julia, and with a (to the extent possible) similar API. There's a lot of code that is repeated across Optim and NLsolve, so I think we can really improve the development work flow and throughput by joining forces formally.

Below, I've CCed everyone who has contributed to this package. The reason is, that I very much prefer that NLsolve (NLSolve?...another discussion) moves into our new home as an MIT licensed package. If people do not agree, we can discuss it, but let's just say that I prefer it that way, and I know other people in the Optim stack do as well.

So this issue is really about the following two questions:

1) for those of you who care, would you support a move?
2) if there is support for 1), would you agree to let the GPL'ed code you've contributed to be re-licensed under the MIT "expat" license? 

Thanks!

cc: @KristofferC @sebastien-villemot @timholy @ChrisRackauckas @matthieugomez @tkelman @sglyon @mlubin

**Comment by KristofferC** [comment]
1) I support a move since the LineSearch and "DifferentiableFunction" stuff is nicely shared.

2) I agree to relicense the code I have added to NLsolve under the MIT license.

**Comment by sebastien-villemot** [comment]
1. I have no opinion.
2. I agree to relicense the code I have added to NLsolve under the MIT license.

**Comment by tkelman** [comment]
sure. my contributions here were so small as to not seem copyrightable, but I agree to relicense.

**Comment by sglyon** [comment]
1. Also no opinion
2. I agree to relicense the code I have contributed under the MIT license.

Thanks @sebastien-villemot for getting this started and being willing to use MIT!

**Comment by pkofod** [comment]
I think most major contributors have agreed, but we can wait and see. I think it would be great to have optim and nlsolve together in an org, so very excited to see that great feedback on the request here.

**Comment by timholy** [comment]
I agree to relicense the code I have added to NLsolve under the MIT license.

**Comment by matthieugomez** [comment]
So do I

**Comment by ChrisRackauckas** [comment]
I also agree.

**Comment by sglyon** [comment]
Excellent, once we hear from @mlubin we are good to go!

@pkofod how do you want to handle this? One option would be to give me write (maybe need admin?) permissions in the new org so I can make the transfer. Are you ok with that?

**Comment by mlubin** [comment]
Ok from me.

**Comment by tkelman** [comment]
There's no code here derived from other sources, is there?

**Comment by sglyon** [comment]
@sebastien-villemot wrote most of the package, so I'll defer to him (and anyone else who knows the answer!)

**Comment by sebastien-villemot** [comment]
I don’t remember all the details, but since I put a `LICENSE.md` file with me as the only copyright holder and a GPL license, I must have meant it (I am a Debian Developer, so I am serious on licensing issues ☺).

Of course I cannot tell for the code contributed by others.

**Comment by sglyon** [comment]
Any objections (from those who haven't already approved)?

If not I'll make the merge soon

**Comment by sglyon** [comment]
Thank you all. 

Transfer completed.

**Comment by sebastien-villemot** [comment]
Thanks. And please go ahead with the modification of `LICENSE.md`.
