### ISSUE TITLE
Fixed-point Iteration methods

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaNLSolvers/NLsolve.jl#88]
It would be nice to have methods like:

https://users.wpi.edu/~walker/Papers/Walker-Ni,SINUM,V49,1715-1735.pdf

also available through NLSolve.jl.

**Comment by sglyon** [comment]
I'll put it on the wishlist!

**Comment by cortner** [comment]
@antoine-levitt, maybe you have lots of spare time on your hand ;)

**Comment by antoine-levitt** [comment]
That no, but I do have a project for which I need this in julia, so once I have a decent implementation that's a good place to put it, thanks for the suggestion!

**Comment by antoine-levitt** [comment]
Done, see https://github.com/JuliaNLSolvers/NLsolve.jl/pull/101. Comments very welcome!

**Comment by pkofod** [comment]
@ChrisRackauckas you can thank @antoine-levitt for fullfilling your wishes!
